name: Android CI

on:
  pull_request:
    paths-ignore:
      - '**.md'

jobs:

  buildDebugApk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
         distribution: 'zulu'
         java-version: '11'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.2.2
        cache-read-only: false

      - name: Build with Gradle
        run: ./gradlew build --dry-run
