name: Push Android CI

on:
  push:
    paths-ignore:
      - '**.md'

jobs:

  buildDebugApk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Branch Name Test
        run: echo "${{github.ref_name}}"
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.2.2
        with:
          cache-read-only:  ${{ github.ref_name != 'main' &&  github.ref_name != 'develop'}}
      - name: Build with Gradle
        run: ./gradlew build --dry-run
